# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-ee9vq3-1UqcnfweP0l08SJ97yn-PLNf
"""

import zipfile
import os

# 1. Unzip the data
if not os.path.exists('dataset'):
    with zipfile.ZipFile('dataset.zip', 'r') as zip_ref:
        zip_ref.extractall('.')
    print("✅ Data Unzipped!")

# 2. Run the training
!python train.py

import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
from google.colab import files
import io
import matplotlib.pyplot as plt

# 1. Load the trained "Brain"
# We wrap this in a try-except just in case the file name varies
try:
    model = load_model('brain_tumor_model.h5')
    print("✅ Model loaded successfully.")
except:
    print("❌ Model not found. Make sure 'brain_tumor_model.h5' is in the files panel.")

def predict_tumor():
    # 2. Upload the image
    print("--- Upload an MRI Image ---")
    uploaded = files.upload()

    for filename in uploaded.keys():
        # 3. Preprocessing (Making the image look like the training data)
        path = filename

        # Load image, resize to 224x224, and convert to grayscale
        img = image.load_img(path, target_size=(224, 224), color_mode='grayscale')

        # Convert to an array of numbers
        img_array = image.img_to_array(img)

        # Normalize (Divide by 255, just like in training!)
        img_array /= 255.0

        # Add the "Batch Dimension"
        # The model expects a list of images, even if it's just one.
        # Shape becomes (1, 224, 224, 1)
        img_batch = np.expand_dims(img_array, axis=0)

        # 4. The Prediction
        prediction = model.predict(img_batch)

        # 5. Interpret the Result
        # The model outputs a probability between 0 and 1.
        # > 0.5 means "Tumor" (Class 1)
        # < 0.5 means "Healthy" (Class 0)
        confidence = prediction[0][0]

        plt.imshow(img, cmap='gray')
        plt.axis('off')
        plt.show()

        print(f"🧠 AI Confidence Score: {confidence:.4f}")

        if confidence > 0.5:
            print("🚨 DIAGNOSIS: TUMOR DETECTED")
        else:
            print("✅ DIAGNOSIS: HEALTHY")

# Run the function
predict_tumor()

import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
from google.colab import files
import io
import matplotlib.pyplot as plt

# 1. Load the trained "Brain"
# We wrap this in a try-except just in case the file name varies
try:
    model = load_model('brain_tumor_model.h5')
    print("✅ Model loaded successfully.")
except:
    print("❌ Model not found. Make sure 'brain_tumor_model.h5' is in the files panel.")

def predict_tumor():
    # 2. Upload the image
    print("--- Upload an MRI Image ---")
    uploaded = files.upload()

    for filename in uploaded.keys():
        # 3. Preprocessing (Making the image look like the training data)
        path = filename

        # Load image, resize to 224x224, and convert to grayscale
        img = image.load_img(path, target_size=(224, 224), color_mode='grayscale')

        # Convert to an array of numbers
        img_array = image.img_to_array(img)

        # Normalize (Divide by 255, just like in training!)
        img_array /= 255.0

        # Add the "Batch Dimension"
        # The model expects a list of images, even if it's just one.
        # Shape becomes (1, 224, 224, 1)
        img_batch = np.expand_dims(img_array, axis=0)

        # 4. The Prediction
        prediction = model.predict(img_batch)

        # 5. Interpret the Result
        # The model outputs a probability between 0 and 1.
        # > 0.5 means "Tumor" (Class 1)
        # < 0.5 means "Healthy" (Class 0)
        confidence = prediction[0][0]

        plt.imshow(img, cmap='gray')
        plt.axis('off')
        plt.show()

        print(f"🧠 AI Confidence Score: {confidence:.4f}")

        if confidence > 0.5:
            print("🚨 DIAGNOSIS: TUMOR DETECTED")
        else:
            print("✅ DIAGNOSIS: HEALTHY")

# Run the function
predict_tumor()

"""# New Section"""
